spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wn_sec
    username: root
    password: 123456
  jpa:
    show-sql: true
  main:
    allow-circular-references: true
jwt:
  secretKey: 12345678